version: '3'

services:
  websocket:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: websocket
    ports:
      - "8080:3000"
    env_file:
      - .env
    networks:
      - websocket
      - consul

networks:
  consul:
    external: 
      name: consul_consul
  websocket:
    driver: bridge
