# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usermanagement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14usermanagement.proto\x12\x0eusermanagement\x1a\x1fgoogle/protobuf/timestamp.proto\".\n\x14UserExistenceRequest\x12\x16\n\x0eparticipant_id\x18\x01 \x01(\t\",\n\x15UserExistenceResponse\x12\x13\n\x0buser_exists\x18\x01 \x01(\x08\x32r\n\x0bUserService\x12\x63\n\x12\x43heckUserExistence\x12$.usermanagement.UserExistenceRequest\x1a%.usermanagement.UserExistenceResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usermanagement_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USEREXISTENCEREQUEST._serialized_start=73
  _USEREXISTENCEREQUEST._serialized_end=119
  _USEREXISTENCERESPONSE._serialized_start=121
  _USEREXISTENCERESPONSE._serialized_end=165
  _USERSERVICE._serialized_start=167
  _USERSERVICE._serialized_end=281
# @@protoc_insertion_point(module_scope)
