swagger: '2.0'
info:
  version: 1.0.0
  title: Quiz QCM API
  description: API for Quiz QCM game between duos
  termsOfService: 'http://quizqcmapi.com/terms'
  contact:
    name: Armel DREY
    email: armeldrey@gmail.com
    url: 'http://bbio.com'
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /questions:
    get:
      summary: Get all questions
      responses:
        200:
          description: Success

    post:
      summary: Create a new question
      parameters:
        - in: body
          name: question
          description: Question object
          schema:
            $ref: '#/definitions/Question'
      responses:
        201:
          description: Success

  /questions/{question_id}:
    get:
      summary: Get a specific question
      parameters:
        - in: path
          name: question_id
          type: string
          required: true
          description: ID of the question
      responses:
        200:
          description: Success

    put:
      summary: Update a specific question
      parameters:
        - in: path
          name: question_id
          type: string
          required: true
          description: ID of the question
        - in: body
          name: question
          description: Updated question object
          schema:
            $ref: '#/definitions/Question'
      responses:
        200:
          description: Success

    delete:
      summary: Delete a specific question
      parameters:
        - in: path
          name: question_id
          type: string
          required: true
          description: ID of the question
      responses:
        200:
          description: Success

  /participants:
    get:
      summary: Get all participants
      responses:
        200:
          description: Success
    post:
      summary: Create a new participant
      parameters:
        - in: body
          name: participant
          description: Participant object
          schema:
            $ref: '#/definitions/Participant'
      responses:
        201:
          description: Success

  /participants/{participant_id}:
    get:
      summary: Get a specific participant
      parameters:
        - in: path
          name: participant_id
          type: string
          required: true
          description: ID of the participant
      responses:
        200:
          description: Success

    put:
      summary: Update a specific participant
      parameters:
        - in: path
          name: participant_id
          type: string
          required: true
          description: ID of the participant
        - in: body
          name: participant
          description: Updated participant object
          schema:
            $ref: '#/definitions/Participant'
      responses:
        200:
          description: Success

    delete:
      summary: Delete a specific participant
      parameters:
        - in: path
          name: participant_id
          type: string
          required: true
          description: ID of the participant
      responses:
        200:
          description: Success
  
  /challenges:
    get:
      summary: Get all challenges
      responses:
        200:
          description: Success

    post:
      summary: Create a new challenge
      parameters:
        - in: body
          name: challenge
          description: Challenge object
          schema:
            $ref: '#/definitions/Challenge'
      responses:
        201:
          description: Success

  /challenges/{challenge_id}:
    get:
      summary: Get a specific challenge
      parameters:
        - in: path
          name: challenge_id
          type: string
          required: true
          description: ID of the challenge
      responses:
        200:
          description: Success

definitions:
  Question:
    type: object
    properties:
      question:
        type: string
        description: The question text
      options:
        type: array
        items:
          type: string
        description: The list of answer options
      answer:
        type: string
        description: The correct answer

  Participant:
    type: object
    properties:
      name:
        type: string
        description: The participant's name

  Challenge:
    type: object
    properties:
      challenger:
        type: string
        description: The challenger's name
      challenged:
        type: string
        description: The challenged's name
      winner:
        type: string
        description: The winner's name
      is_started:
        type: boolean
        default: false
        description: The challenge is started
      is_ended:
        type: boolean
        default: false
        description: The challenge is ended
      launched_date:
        type: string 
        format: date-time
        description: The launched date
      started_date:
        type: string 
        format: date-time
        default: null
        description: The started date
      ended_date:
        type: string 
        format: date-time
        default: null
        description: The ended date
