swagger: '2.0'
info:
  version: 1.0.0
  title: Quiz QCM API
  description: API for Quiz QCM game between duos
  termsOfService: 'http://quizqcmapi.com/terms'
  contact:
    name: Armel DREY
    email: armeldrey@gmail.com
    url: 'http://bbio.com'
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /questions:
    get:
      summary: Get all questions
      responses:
        200:
          description: Success

    post:
      summary: Create a new question
      parameters:
        - in: body
          name: question
          description: Question object
          schema:
            $ref: '#/definitions/Question'
      responses:
        200:
          description: Success

  /questions/{question_id}:
    get:
      summary: Get a specific question
      parameters:
        - in: path
          name: question_id
          type: string
          required: true
          description: ID of the question
      responses:
        200:
          description: Success

    put:
      summary: Update a specific question
      parameters:
        - in: path
          name: question_id
          type: string
          required: true
          description: ID of the question
        - in: body
          name: question
          description: Updated question object
          schema:
            $ref: '#/definitions/Question'
      responses:
        200:
          description: Success

    delete:
      summary: Delete a specific question
      parameters:
        - in: path
          name: question_id
          type: string
          required: true
          description: ID of the question
      responses:
        200:
          description: Success

  /participants:
    post:
      summary: Create a new participant
      parameters:
        - in: body
          name: participant
          description: Participant object
          schema:
            $ref: '#/definitions/Participant'
      responses:
        200:
          description: Success

  /participants/{participant_id}:
    get:
      summary: Get a specific participant
      parameters:
        - in: path
          name: participant_id
          type: string
          required: true
          description: ID of the participant
      responses:
        200:
          description: Success

    put:
      summary: Update a specific participant
      parameters:
        - in: path
          name: participant_id
          type: string
          required: true
          description: ID of the participant
        - in: body
          name: participant
          description: Updated participant object
          schema:
            $ref: '#/definitions/Participant'
      responses:
        200:
          description: Success

    delete:
      summary: Delete a specific participant
      parameters:
        - in: path
          name: participant_id
          type: string
          required: true
          description: ID of the participant
      responses:
        200:
          description: Success

definitions:
  Question:
    type: object
    properties:
      question:
        type: string
        description: The question text
      options:
        type: array
        items:
          type: string
        description: The list of answer options
      answer:
        type: string
        description: The correct answer

  Participant:
    type: object
    properties:
      name:
        type: string
        description: The participant's name
