name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.LIGHTSAIL_PUBLIC_IP }} >> ~/.ssh/known_hosts
      env:
        LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}

    - name: Copy files to Lightsail instance
      run: |
        ls -la
        pwd
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./* ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }}:/home/bitnami/plantio/biogame
        touch ./.env
        echo "MONGODB_URI=${{ secrets.APP_MONGODB_URI }}" >> ./.env
        echo "PORT=${{ secrets.APP_PORT }}" >> ./.env
        echo "RANDOM_QUESTIONS=${{ secrets.APP_RANDOM_QUESTIONS }}" >> ./.env
        echo "JWT_TOKEN_SECRET=${{ secrets.APP_JWT_SECRET }}" >> ./.env
        echo "CONSUL_IP=${{ secrets.APP_CONSUL_IP }}" >> ./.env
        echo "CONSUL_PORT=${{ secrets.APP_CONSUL_PORT }}" >> ./.env
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./.env ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }}:/home/bitnami/plantio/biogame
        ls -la       
      env:
        LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
        LIGHTSAIL_PUBLIC_IP: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
        APP_MONGODB_URI: ${{ secrets.APP_MONGODB_URI }}
        APP_PORT: ${{ secrets.APP_PORT }}
        APP_RANDOM_QUESTIONS: ${{ secrets.APP_RANDOM_QUESTIONS }}
        APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}
        APP_CONSUL_IP: ${{ secrets.APP_CONSUL_IP }}
        APP_CONSUL_PORT: ${{ secrets.APP_CONSUL_PORT }}


    # - name: Kill old proccess on same port
    #   run: |
    #     touch myperm.pem
    #     echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > myperm.pem
    #     chmod 600 myperm.pem
    #     ssh -i myperm.pem ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }} "docker-compose down"
    #   env:
    #     LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
    #     LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
    #     LIGHTSAIL_PUBLIC_IP: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}


    # - name: SSH into Lightsail instance and deploy
    #   run: |
    #     touch myperm.pem
    #     echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > myperm.pem
    #     chmod 600 myperm.pem
    #     # ssh -i myperm.pem ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }} 'cd /home/bitnami/plantio/biogame && npm install && npm start > /dev/null 2>&1 &'
    #     ssh -i myperm.pem ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }} 'cd /home/bitnami/plantio/biogame && npm install && nohup npm start > /dev/null 2>&1 &'
    #   env:
    #     LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
    #     LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
    #     LIGHTSAIL_PUBLIC_IP: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
    #     APP_MONGODB_URI: ${{ secrets.APP_MONGODB_URI }}
    #     APP_PORT: ${{ secrets.APP_PORT }}
    #     APP_RANDOM_QUESTIONS: ${{ secrets.APP_RANDOM_QUESTIONS }}
    #     APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}


    - name: Build Docker container on Lightsail
      run: |
        # touch myperm.pem
        # echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > myperm.pem
        # chmod 600 myperm.pem
        # ssh -i myperm.pem ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }} 'cd /home/bitnami/plantio/biogame && npm install && npm start > /dev/null 2>&1 &'
        # ssh -i myperm.pem ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }} 'cd /home/bitnami/plantio/biogame && npm install && nohup npm start > /dev/null 2>&1 &'
        ssh -i ~/.ssh/id_rsa ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }} 'cd /home/bitnami/plantio/biogame && docker-compose down && docker-compose up -d --build'
      env:
        LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
        LIGHTSAIL_PUBLIC_IP: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
        APP_MONGODB_URI: ${{ secrets.APP_MONGODB_URI }}
        APP_PORT: ${{ secrets.APP_PORT }}
        APP_RANDOM_QUESTIONS: ${{ secrets.APP_RANDOM_QUESTIONS }}
        APP_JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}


