name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.LIGHTSAIL_PUBLIC_IP }} >> ~/.ssh/known_hosts
      env:
        LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}

    - name: Copy files to Lightsail instance
      run: |
        ls -la
        touch .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "RANDOM_QUESTIONS=${{ secrets.RANDOM_QUESTIONS }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ./* ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }}:/home/bitnami/plantio
      env:
        LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
        LIGHTSAIL_PUBLIC_IP: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
        MONGODB_URI: ${{ secrets.APP_MONGODB_URI }}
        PORT: ${{ secrets.APP_PORT }}
        RANDOM_QUESTIONS: ${{ secrets.APP_RANDOM_QUESTIONS }}
        JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}


    - name: Verify .env file content
      run: |
        echo "${{ secrets.LIGHTSAIL_USERNAME }}"
        cat .env
      env:
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
        LIGHTSAIL_PUBLIC_IP: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
        MONGODB_URI: ${{ secrets.APP_MONGODB_URI }}
        PORT: ${{ secrets.APP_PORT }}
        RANDOM_QUESTIONS: ${{ secrets.APP_RANDOM_QUESTIONS }}
        JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}


    - name: SSH into Lightsail instance and deploy
      run: |
        touch myperm.pem
        echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > myperm.pem
        chmod 600 myperm.pem
        cat .env
        pwd
        ls -la
        pwd
        ssh -i myperm.pem ${{ secrets.LIGHTSAIL_USERNAME }}@${{ secrets.LIGHTSAIL_PUBLIC_IP }} 'cd /home/bitnami/plantio && npm install && npm start'
      env:
        LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        LIGHTSAIL_USERNAME: ${{ secrets.LIGHTSAIL_USERNAME }}
        LIGHTSAIL_PUBLIC_IP: ${{ secrets.LIGHTSAIL_PUBLIC_IP }}
        MONGODB_URI: ${{ secrets.APP_MONGODB_URI }}
        PORT: ${{ secrets.APP_PORT }}
        RANDOM_QUESTIONS: ${{ secrets.APP_RANDOM_QUESTIONS }}
        JWT_SECRET: ${{ secrets.APP_JWT_SECRET }}


